version: '3.1'
services:

    redis:
        image: redis
        container_name: redis
        restart: always
        env_file: ./docker/env

    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        env_file: ./docker/env
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/etc/mysql:/etc/mysql/conf.d
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8080:80

    nginx:
        build: ./docker/nginx
        container_name: nginx
        restart: always
        command: [ "sh", "-c", "./docker/nginx/init.sh; nginx -g 'daemon off;'" ]
        volumes:
            - ./src:/var/www/dev/
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
            - ./docker/nginx/ssl:/etc/ssl/certs
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443

    php:
        build: ./docker/php
        container_name: php
        depends_on:
            - mysql
        command: [ "sh", "-c", "./docker/php/init.sh; php-fpm" ]
        volumes:
            - ./src:/var/www/dev/
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        ports:
            - 9000:9000
